events {
}

http {
  include       mime.types;
  default_type  application/octet-stream;

  server {
    listen 80;
    server_name localhost;

    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;

      add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
      add_header Pragma "no-cache";
      expires off;
    }

    # location /version.json {
    #   root /usr/share/nginx/html; 
    #   try_files $uri =404;

      
    #   add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    #   add_header Pragma "no-cache";
    #   expires off;
    # }


    location /js/ {
      add_header Content-Type application/javascript;
      add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
      add_header Pragma "no-cache";
      expires off;
    }

    location ~* \.(png|jpg|jpeg|gif|ico|svg)$ {
      root /usr/share/nginx/html;
      try_files $uri =404;       

      add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
      add_header Pragma "no-cache";
      expires off;
      # try_files $uri =404;
      # expires 30d;
      # add_header Cache-Control "public, max-age=2592000, immutable";
    }
  }
}